//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciclos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ciclos()
        {
            this.Muestras = new HashSet<Muestras>();
            this.Lotes = new HashSet<Lotes>();
            this.ParteCiclo = new HashSet<ParteCiclo>();
        }
    
        public string Horno { get; set; }
        public int No_Ciclo { get; set; }
        public int PK_Usuario { get; set; }
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public Nullable<int> vacio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Muestras> Muestras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lotes> Lotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParteCiclo> ParteCiclo { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
