//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lotes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lotes()
        {
            this.Piezas = new HashSet<Piezas>();
        }
    
        public int PK_Lote { get; set; }
        public string Horno { get; set; }
        public int No_Ciclo { get; set; }
        public int PK_Usuario { get; set; }
        public string FechaAlta { get; set; }
    
        public virtual Ciclos Ciclos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Piezas> Piezas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
