//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuestrasHornosEntities : DbContext
    {
        public MuestrasHornosEntities()
            : base("name=MuestrasHornosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ciclos> Ciclos { get; set; }
        public virtual DbSet<Defectos> Defectos { get; set; }
        public virtual DbSet<inicio> inicio { get; set; }
        public virtual DbSet<Lotes> Lotes { get; set; }
        public virtual DbSet<Muestras> Muestras { get; set; }
        public virtual DbSet<ParteCiclo> ParteCiclo { get; set; }
        public virtual DbSet<Piezas> Piezas { get; set; }
        public virtual DbSet<PruebaPieza> PruebaPieza { get; set; }
        public virtual DbSet<Pruebas> Pruebas { get; set; }
        public virtual DbSet<Sensores> Sensores { get; set; }
        public virtual DbSet<TipoSensor> TipoSensor { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
